apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend 
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: cd-flow-backend 
          servicePort: 80
