{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-09T16:41:04Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.19
    sha: 977aeaedb3982163d0d8520181390c57931bd08b
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: cc971f11f7947944b88dcbe3d058686304d4c589
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      dealing with update the right objects
    sha: 3c0fdc339110f6aeda80a7d74425c4fe58e152af
  gitHttpUrl: https://github.com/salaboy/cd-flow-backend
  gitOwner: salaboy
  gitRepository: cd-flow-backend
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/cd-flow-backend/releases/tag/v0.0.20
  version: v0.0.20
status: {}
 
{{- end }}
