{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-13T16:28:38Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.22
    sha: 253490551702561b73a5c22a07d6af0247b020dd
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: cf13b9020184960dd7d499aedc0f55b063a565df
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding repo url to metrics
    sha: 591d9131a1f15166be058b5e15d30e86e872f12f
  gitHttpUrl: https://github.com/salaboy/cd-flow-backend
  gitOwner: salaboy
  gitRepository: cd-flow-backend
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/cd-flow-backend/releases/tag/v0.0.23
  version: v0.0.23
status: {}
 
{{- end }}
