{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-14T15:03:04Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.25
    sha: 5b30f519a48df07ce1c93e44d50e64cedf49a203
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: cb767b7c8fb200818f7a54fa84fbf3728f5fc842
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding env endpoints
    sha: 79d35275c0faf26fed1cc30c618b00539ce5058b
  gitHttpUrl: https://github.com/salaboy/cd-flow-backend
  gitOwner: salaboy
  gitRepository: cd-flow-backend
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/cd-flow-backend/releases/tag/v0.0.26
  version: v0.0.26
status: {}
 
{{- end }}
